bharath_expo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^web/', include(('web.urls', 'web'), namespace="web")),

    url(r'^$',general_views.app,name='app'),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/android/$',general_views.download_app,name='download_app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/shop/create/$',general_views.create_shop,name='create_shop'),
    url(r'^app/shop/switch/$', general_views.switch_shop, name='switch_shop'),
    url(r'^app/theme/switch/$', general_views.switch_theme, name='switch_theme'),
    url(r'^app/shop/delete/(?P<pk>.*)/$', general_views.delete_shop, name='delete_shop'),
    url(r'^app/report/$',general_views.reports,name='report'),

    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'),

    url(r'^app/customers/', include(('customers.urls','customers'), namespace="customers")),
    url(r'^app/products/', include(('products.urls','products'), namespace="products")),
    url(r'^app/sales/', include(('sales.urls','sales'), namespace="sales")),
    url(r'^app/staffs/', include(('staffs.urls','staffs'), namespace='staffs')),
    url(r'^app/vendors/', include(('vendors.urls','vendors'), namespace='vendors')),
    url(r'^app/purchases/', include(('purchases.urls', 'purchases'), namespace='purchases')),
    url(r'^app/finance/', include(('finance.urls', 'finance'), namespace="finance")),
    url(r'^app/tasks/', include(('tasks.urls','tasks'), namespace="tasks")),
    url(r'^app/distributors/', include(('distributors.urls', 'distributors'), namespace="distributors")),

    url(r'^app/users/', include(('users.urls','users'), namespace="users")),

    url(r'^app/reports/', include(('reports.urls','reports'), namespace="reports")),

    url(r'^app/barcode/create/(?P<code>.*)/$', general_views.create_barcode, name='create_barcode'),

    url(r'^create-shop-request/$', general_views.create_shop_request, name="create_shop_request"),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

finance/urls.py
from django.conf.urls import url
from . import views
from finance.autocomplete_light_registry import StaffAutocomplete, TaxCategoryAutocomplete


urlpatterns = [
    url(r'^tax-category-autocomplete/$',TaxCategoryAutocomplete.as_view(create_field='tax'),name='tax_category_autocomplete'),

    url(r'^$', views.dashboard,name='dashboard'), 

    url(r'^bank-account/create/$',views.create_bank_account,name='create_bank_account'),
    url(r'^bank-account/edit(?P<pk>.*)/$',views.edit_bank_account,name='edit_bank_account'),
    url(r'^bank-accounts/$',views.bank_accounts,name='bank_accounts'),
    url(r'^bank-account/view/(?P<pk>.*)/$',views.bank_account,name='bank_account'),
    url(r'^bank-account/delete/(?P<pk>.*)/$',views.delete_bank_account,name='delete_bank_account'),
    url(r'^bank-account/delete-selected/$', views.delete_selected_bank_accounts, name='delete_selected_bank_accounts'),

    url(r'^cash-account/create/$',views.create_cash_account,name='create_cash_account'),
    url(r'^cash-account/edit/(?P<pk>.*)$',views.edit_cash_account,name='edit_cash_account'),
    url(r'^cash-accounts/$',views.cash_accounts,name='cash_accounts'),
    url(r'^cash-account/view/(?P<pk>.*)/$',views.cash_account,name='cash_account'),
    url(r'^cash-account/delete/(?P<pk>.*)$',views.delete_cash_account,name='delete_cash_account'),
    url(r'^cash-account/delete-selected/$', views.delete_selected_cash_accounts, name='delete_selected_cash_accounts'),

    url(r'^transaction-category/create/$',views.create_transaction_category,name='create_transaction_category'),
    url(r'^transaction-category/edit/(?P<pk>.*)/$',views.edit_transaction_category,name='edit_transaction_category'),
    url(r'^transaction-categories/',views.transaction_categories,name='transaction_categories'),
    url(r'^transaction-category/view/(?P<pk>.*)/$',views.transaction_category,name='transaction_category'),
    url(r'^transaction-category/delete/(?P<pk>.*)/$',views.delete_transaction_category,name='delete_transaction_category'),
    url(r'^transaction-category/delete-selected/$', views.delete_selected_transaction_categories, name='delete_selected_transaction_categories'),

    url(r'^income/create/$',views.create_income,name='create_income'),
    url(r'^income/edit/(?P<pk>.*)/$',views.edit_income,name='edit_income'),
    
    url(r'^transactions/$',views.transactions,name='transactions'),
    url(r'^transaction/view/(?P<pk>.*)/$',views.transaction,name='transaction'),
    url(r'^transaction/delete/(?P<pk>.*)/$',views.delete_transaction,name='delete_transaction'),
    url(r'^transaction/delete-selected/$', views.delete_selected_transactions, name='delete_selected_transactions'),

    url(r'^expense/create/$',views.create_expense,name='create_expense'),
    url(r'^expense/edit(?P<pk>.*)/$',views.edit_expense,name='edit_expense'),
    
    url(r'^staff-autocomplete/$',StaffAutocomplete.as_view(),name='staff_autocomplete'),

    url(r'^tax-category/create/$', views.create_tax_category, name='create_tax_category'),
    url(r'^tax-categories/$', views.tax_categories, name='tax_categories'),
    url(r'^tax-category/edit/(?P<pk>.*)/$', views.edit_tax_category, name='edit_tax_category'),
    url(r'^tax-category/(?P<pk>.*)/$', views.tax_category, name='tax_category'),
    url(r'^delete-tax-category/(?P<pk>.*)/$', views.delete_tax_category, name='delete_tax_category'),
    url(r'^tax-category/delete-selected/$', views.delete_selected_tax_categories, name='delete_selected_tax_categories'),

    url(r'^create-salary-payment/$',views.create_salary_payment,name='create_salary_payment'),
    url(r'^create-salary-payment-popup/$',views.create_salary_payment_ajax,name='create_salary_payment_ajax'),
    url(r'^salary-payment/edit/(?P<pk>.*)/$',views.edit_salary_payment,name='edit_salary_payment'),
    url(r'^salary-payments/$',views.salary_payments,name='salary_payments'),

    url(r'^cash-transfer/create/$',views.create_cash_transfer,name='create_cash_transfer'),
    url(r'^cash-transfers/$',views.cash_transfers,name='cash_transfers'),
    url(r'^cash-transfer/(?P<pk>.*)/$',views.cash_transfer,name='cash_transfer'),
    url(r'^delete-cash-transfer/(?P<pk>.*)/$',views.delete_cash_transfer,name='delete_cash_transfer'),
    url(r'^delete-selected-cash-transfers/$', views.delete_selected_cash_transfers, name='delete_selected_cash_transfers'),

    url(r'^get-cash-account-list/$',views.get_cash_account_list,name='get_cash_account_list'),
    url(r'^get-cash-balance/$',views.get_cash_balance,name='get_cash_balance'),

    url(r'^balance-sheet/create/$',views.create_balance_sheet,name='create_balance_sheet'),
    url(r'^balance-sheet/$',views.balance_sheet,name='balance_sheet'),


    url(r'^get-tax/$',views.get_tax,name='get_tax'),

]

sales/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from sales.views import SaleAutocomplete,ReturnableProductAutocomplete


urlpatterns = [               
    url(r'^sale-autocomplete/$',SaleAutocomplete.as_view(),name='sale_autocomplete'),
    url(r'^returnable_products-autocomplete/$',ReturnableProductAutocomplete.as_view(),name='returnable_product_autocomplete'),
    
    url(r'^$', views.dashboard,name='dashboard'), 
    url(r'^print-report/$', views.print_report,name='print_report'), 
    url(r'^taxed-sale-items/$', views.taxed_sale_items,name='taxed_sale_items'),
    url(r'^export-report/$', views.export_report,name='export_report'),
    
    url(r'^sale/create/$',views.create,name='create'),
    url(r'^sale/views/$',views.sales,name='sales'),
    url(r'^sale/edit/(?P<pk>.*)/$',views.edit,name='edit'),
    url(r'^sale/view/(?P<pk>.*)/$',views.sale,name='sale'),
    url(r'^sale/delete/(?P<pk>.*)/$',views.delete,name='delete'),
    url(r'^sale/delete-selected/$', views.delete_selected_sales, name='delete_selected_sales'),
    url(r'^invoice/(?P<pk>.*)/$',views.print_sale,name='print'),
    url(r'^email/(?P<pk>.*)/$',views.email_sale,name='email_sale'),
    url(r'^return-sale/views/$',views.return_sales,name='return_sales'),

    url(r'^collect-amount/create/$', views.create_collect_amount, name='create_collect_amount'),
    url(r'^collect-amount/view/(?P<pk>.*)/$', views.collect_amount, name='collect_amount'),
    url(r'^collect-amount/edit/(?P<pk>.*)/$', views.edit_collect_amount, name='edit_collect_amount'),
    url(r'^collect-amounts/$', views.collect_amounts, name='collect_amounts'),
    url(r'^collect-amount/delete/(?P<pk>.*)/$', views.delete_collect_amount, name='delete_collect_amount'),
    url(r'^collect-amount/delete-selected/$', views.delete_selected_collect_amounts, name='delete_selected_collect_amounts'),
    url(r'^collected-amount/print/(?P<pk>.*)/$',views.print_collected_amount,name='print_collected_amount'),
    url(r'^collected-amounts/print/$',views.print_collected_amounts,name='print_collected_amounts'),

    url(r'^customer-payment/create/$', views.create_customer_payment, name='create_customer_payment'),
    url(r'^customer-payment/view/(?P<pk>.*)/$', views.customer_payment, name='customer_payment'),
    url(r'^customer-payment/edit/(?P<pk>.*)/$', views.edit_customer_payment, name='edit_customer_payment'),
    url(r'^customer-payments/$', views.customer_payments, name='customer_payments'),
    url(r'^customer-payment/delete/(?P<pk>.*)/$', views.delete_customer_payment, name='delete_customer_payment'),
    url(r'^customer-payment/delete-selected/$', views.delete_selected_customer_payments, name='delete_selected_customer_payments'),
    url(r'^customer-payment/print/(?P<pk>.*)/$',views.print_customer_payment,name='print_customer_payment'),
    url(r'^customer-payments/print/$',views.print_customer_payments,name='print_customer_payments'),

    url(r'^create-sale-return/$',views.create_sale_return,name='create_sale_return'),
    url(r'^sale-returns/$',views.sale_returns,name='sale_returns'), 
    url(r'^sale-return/(?P<pk>.*)/$', views.sale_return, name='sale_return'),

    url(r'^print-sale-return/(?P<pk>.*)/$', views.print_sale_return, name='print_sale_return'),
    url(r'^delete-sale-return/(?P<pk>.*)/$', views.delete_sale_return, name='delete_sale_return'),

    url(r'^damaged-products/$',views.damaged_products,name='damaged_products'),
    url(r'^create-damaged-product/$',views.create_damaged_product,name='create_damaged_product'),
    
    url(r'^create-product-return/$',views.create_product_return,name='create_product_return'),
    url(r'^product-return/(?P<pk>.*)/$', views.product_return, name='product_return'),
    url(r'^product-returns/$',views.product_returns,name='product_returns'),
    url(r'^delete-product-return/(?P<pk>.*)/$', views.delete_product_return, name='delete_product_return'),
    url(r'^get-sale-items/$', views.get_sale_items,name='get_sale_items'),
    url(r'^get-return-items/$', views.get_return_items,name='get_return_items'),
    url(r'^get-vendor-return-items/$', views.get_vendor_return_items,name='get_vendor_return_items'),
    url(r'^get-customer/$', views.get_customer,name='get_customer'),

    url(r'^estimate/create/$',views.create_estimate,name='create_estimate'),
    url(r'^estimate/views/$',views.estimates,name='estimates'),
    url(r'^estimate/edit/(?P<pk>.*)/$',views.edit_estimate,name='edit_estimate'),
    url(r'^estimate/view/(?P<pk>.*)/$',views.estimate,name='estimate'),
    url(r'^estimate/delete/(?P<pk>.*)/$',views.delete_estimate,name='delete_estimate'),
    url(r'^estimate/delete-selected/$', views.delete_selected_estimates, name='delete_selected_estimates'),
    url(r'^print-estimate/(?P<pk>.*)/$',views.print_estimate,name='print_estimate'),
    url(r'^email-estimate/(?P<pk>.*)/$',views.email_estimate,name='email_estimate'),

    url(r'^stock/report/$',views.stock_report, name='stock_report'),

    url(r'^create-vendor-return/$',views.create_vendor_return,name='create_vendor_return'),
    url(r'^vendor-return/(?P<pk>.*)/$', views.vendor_return, name='vendor_return'),
    url(r'^vendor-returns/$',views.vendor_returns,name='vendor_returns'),
    url(r'^delete-vendor-return/(?P<pk>.*)/$', views.delete_vendor_return, name='delete_vendor_return'), 

    url(r'^purchase-request/create/$',views.create_purchase_request,name='create_purchase_request'),
    url(r'^purchase-request/views/$',views.purchase_requests,name='purchase_requests'),
    url(r'^purchase-request/edit/(?P<pk>.*)/$',views.edit_purchase_request,name='edit_purchase_request'),
    url(r'^purchase-request/view/(?P<pk>.*)/$',views.purchase_request,name='purchase_request'),
    url(r'^purchase-request/delete/(?P<pk>.*)/$',views.delete_purchase_request,name='delete_purchase_request'),
    url(r'^purchase-request/delete-selected/$', views.delete_selected_purchase_requests, name='delete_selected_purchase_requests'),
    url(r'^print-purchase-request/(?P<pk>.*)/$',views.print_purchase_request,name='print_purchase_request'),

    url(r'^purchase-request/returns/$',views.purchase_request_returns,name='purchase_request_returns'),

    url(r'^purchase-request-sale/create/(?P<pk>.*)/$',views.purchase_request_sale_create,name='purchase_request_sale_create'),
    url(r'^cheque-list/views/$',views.cheque_lists,name='cheque_lists'),
    url(r'^cheque_withdraw/(?P<pk>.*)/$',views.cheque_withdraw,name='cheque_withdraw'),
    url(r'^cheque_return/(?P<pk>.*)/$',views.cheque_return,name='cheque_return'),

]

web/urls.py
from django.conf.urls import url,include
from . import views
from web.views import ProductCategoryAutocomplete,WebProductAutocomplete


urlpatterns = [
    url(r'^$', views.index,name='index'), 
    url(r'^product-category-autocomplete/$',ProductCategoryAutocomplete.as_view(),name='product_category_autocomplete'),
    url(r'^web-product-autocomplete/$',WebProductAutocomplete.as_view(),name='web_product_autocomplete'),

    url(r'^create-about/$',views.create_about,name='create_about'),
    url(r'^edit-about/(?P<pk>.*)/$',views.edit_about,name='edit_about'),
    url(r'^view-abouts/$',views.abouts,name='abouts'),
    url(r'^view-about/(?P<pk>.*)/$',views.about,name='about'),
    url(r'^delete-about/(?P<pk>.*)/$',views.delete_about,name='delete_about'),
    url(r'^delete-selected-abouts/$', views.delete_selected_abouts, name='delete_selected_abouts'),

    url(r'^category/create/$',views.create_category,name='create_category'),
    url(r'^categories/$',views.categories,name='categories'),
    url(r'^category/edit/(?P<pk>.*)/$',views.edit_category,name='edit_category'),
    url(r'^category/view/(?P<pk>.*)/$',views.category,name='category'),
    url(r'^category/delete/(?P<pk>.*)/$',views.delete_category,name='delete_category'),
    url(r'^category/delete-selected/$', views.delete_selected_categories, name='delete_selected_categories'),

    url(r'^offer/create/$',views.create_offer,name='create_offer'),
    url(r'^offer/view/$',views.offers,name='offers'),
    url(r'^offer/edit/(?P<pk>.*)/$',views.edit_offer,name='edit_offer'),
    url(r'^offer/view/(?P<pk>.*)/$',views.offer,name='offer'),
    url(r'^offer/delete/(?P<pk>.*)/$',views.delete_offer,name='delete_offer'),
    url(r'^offer/delete-selected-offers/$', views.delete_selected_offers, name='delete_selected_offers'), 

    url(r'^product/create/$',views.create_product,name='create_product'),
    url(r'^product/views/$',views.products,name='products'),
    url(r'^product/edit/(?P<pk>.*)/$',views.edit_product,name='edit_product'),
    url(r'^product/view/(?P<pk>.*)/$',views.product,name='product'),
    url(r'^product/delete/(?P<pk>.*)/$',views.delete_product,name='delete_product'),
    url(r'^product/delete-selected/$', views.delete_selected_products, name='delete_selected_products'),

    url(r'^get-products/$',views.get_products,name='get_products'),

]

templates/finance/balance_sheet.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{ title }}</h2>
            </div>
            <div class="action-header palette-theme {{ current_theme }} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{ title }}</div>

                <div class="ah-search">
                    <form method="get" action="{% url 'finance:transactions' %}">
                        <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

                        <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                        <input type="submit" class="hidden"/>
                    </form>
                </div>

            </div>
        </div>

        <div class="card">

            <div class="table-responsive">
                <table id="data-table-basic" class="table table-striped table-vmiddle">
                    <thead>
                    <tr>
                        <th style='width: 40%' data-column-id="name" data-type="numeric">Asset</th>
                        <th style='width: 10%' data-column-id="debit" data-type="numeric">Rs</th>
                        <th style='width: 40%' data-column-id="credit" data-type="numeric">Liabilities</th>
                        <th style='width: 10%' data-column-id="credit" data-type="numeric">Rs</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>Cash in Bank</td>
                        <td>{{ bank_debit }}</td>
                        <td>Capital Account</td>
                        <td>{{ capital_account }}</td>
                    </tr>
                    <tr>
                        <td>Cash in Hand</td>
                        <td>{{ cash_debit }}</td>
                        <td>Bank Overdraft</td>
                        <td>{{ bank_credit }}</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td>Loan And Liability</td>
                        <td>{{ cash_credit }}</td>
                    </tr>
                    
                    <tr>
                        <td></td>
                        <td>{{ debit }}</td>
                        <td></td>
                        <td>{{ credit }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>

        </div>
    </section>
{% endblock %}

{% block static %}
    {% load static %}
    <style>
        td {
            border-right: 2px solid black;
        }
    </style>
{% endblock %}

templates/finance/transactions.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{title}}</h2>
            </div>
        	<div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{title}}</div>
    
                <div class="ah-search">
                    <form method="get" action="{% url 'finance:transactions' %}">
                        <input name="q" type="text" placeholder="Start typing..." class="ahs-input">
    
                        <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                        <input type="submit" class="hidden" />
                    </form>
                </div>
    
                <ul class="ah-actions actions a-alt">
                    <li>
                        <a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
                            <i class="zmdi zmdi-search"></i>
                        </a>
                    </li>
                    
                    <li>
                        <a title="Filter" class="filter_button" href="">
                            <i class="zmdi zmdi-filter-list"></i>
                        </a>
                    </li>
                    
                    
                    {% if instances %}
    
                    <li>
                        <a title="Select All" class="check_all" href="">
                            <i class="zmdi zmdi-select-all"></i>
                        </a>
                    </li>
                    
                    <li>
                        <a title="Delete selected categories" data-id="" href="{% url 'finance:delete_selected_transactions' %}" data-text="{{confirm_delete_selected_message}}" data-title="Are you sure?" class="action-button reload selected-items-button">
                            <i class="zmdi zmdi-delete"></i>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
		</div>

        <div class="card">
			
			{% if instances %}
			
            <div class="table-responsive">
                <table id="data-table-basic" class="table table-striped table-vmiddle">
                    <thead>
                        <tr>
                        	<th style="width:20px;"></th>
                            <th data-column-id="date" data-type="numeric">Date</th>
                            <th data-column-id="transaction_category">Transaction Category</th>
                            <th data-column-id="type">Type</th>
                            <th data-column-id="toilet_facility">Mode</th>
                            <th data-column-id="customer">Customer</th>
                            <th data-column-id="sale">Sale</th>
                            <th data-column-id="staff">Staff</th>
                            <th data-column-id="description">Description</th>
                            <th data-column-id="parking_capacity">Amount</th>
                            <th data-column-id="dining_room_capacity">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% load el_pagination_tags %}
                        {% paginate 21 instances %}
                        {% for instance in instances %}
                        <tr class="check_items_row">
                        	<td style="width:20px;">
                        		<div class="checkbox lgi-checkbox m-t-5">
		                            <label>
		                                <input class="check check_item" type="checkbox" value="{{instance.pk}}" name="delete_item">
		                                <i class="input-helper"></i>
		                            </label>
		                        </div>
                        	</td>
                        	<td>{{instance.date|default:"-"}}</td>
                            <td>{{instance.transaction_category|default:"-"}}</td>
                            <td>{{instance.get_transaction_type_display|default:"-"}}</td>
                            <td>{{instance.get_transaction_mode_display|default:"-"}}</td>
                            <td>{{instance.customer|default:"-"}}</td>
                            <td>{{instance.sale|default:"-"}}</td>
                            <td>{{instance.staff_salary.staff.first_name}}</td>
                            <td>{{instance.description|default:"-"}}</td>
                            <td>{{instance.amount|default:"-"}}</td>
                            <td>
                                <a href="{% url 'finance:transaction' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                                {% if instance.transaction_type == "income" %}
                                    {% if instance.collect_amount != NULL%}
                                        <a href="{% url 'sales:edit_collect_amount' pk=instance.collect_amount.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                    {% elif instance.sale != NULL and instance.collect_amount == NULL%}
                                        <a href="{% url 'sales:edit' pk=instance.sale.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                    {% else %}
                                        <a href="{% url 'finance:edit_income' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                    {% endif %}
                                {% endif %}
                                {% if instance.transaction_type == "expense" %}
                                    {% if instance.paid != NULL%}
                                        <a href="{% url 'purchases:edit_paid' pk=instance.paid.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                    {% elif instance.purchase != NULL and instance.paid == NULL%}
                                        <a href="{% url 'purchases:edit_purchase' pk=instance.purchase.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                    {% else %}
                                        <a href="{% url 'finance:edit_expense' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                    {% endif %}
                                {% endif %}
                                <a data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'finance:delete_transaction' pk=instance.pk %}" class="action-button reload btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            
            <!--pagination -->
            <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                {% get_pages %}
                <div class="row">
                    <div class="col-sm-6">
                        <div class="pagination">
                            {% show_pages %}
                        </div>
                    </div>
                    <div class="col-sm-6 infoBar">
                        <div class="infos">
                            Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                        </div>
                    </div>
                </div>
            </div>   
            <!--pagination-->
            {% else %}
                {% include 'includes/not_found.html' %}
            {% endif %}            
        </div>
    </section>
{% endblock %}
{% block filter_box %}
<div class="filter-box">
	 <form method="get" action="{% url 'finance:transactions' %}">
	 	<div class="card">
			<div class="card-header">
		        <h2>Filter <small></small></h2>
		        <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i> Back</span>
		    </div>
		    
			<div class="card-body card-padding add_item_container sale_item_formset">
			 	<div class="form-group fg-line">
		            <label>Query</label>
		            <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
		        </div>
                <div class="form-group fg-line">
                    <label>Transaction Type</label>
                    <select name="transaction_type" id="transaction_type" class="selectpicker">
                        <option value="">All</option>
                        <option value="income">Income</option>
                        <option value="expense">Expense</option>

                    </select>
                </div>
                <div class="form-group fg-line">
                    <label>Year</label>
                    <input name="year" type="text" class="form-control" placeholder="yyyy" />
                </div>
                <div class="form-group fg-line">
                    <label>Month</label>
                    <select name="month" id="id_month" class="selectpicker">
                        <option value="">All</option>
                        <option value="1">January</option>
                        <option value="2">February</option>
                        <option value="3">March</option>
                        <option value="4">April</option>
                        <option value="5">May</option>
                        <option value="6">June</option>
                        <option value="7">July</option>
                        <option value="8">August</option>
                        <option value="9">September</option>
                        <option value="10">October</option>
                        <option value="11">November</option>
                        <option value="12">December</option>

                    </select>
                </div>
                <div class="form-group fg-line">
                    <label>Period</label>
                    <select name="period" id="id_period" class="selectpicker">
                        <option value="">All</option>
                        <option value="today">Today</option>
                        <option value="month">Month</option>
                        <option value="year">Year</option>
                    </select>
                </div>
                <div class="form-group fg-line">
                    <label>Date</label>
                    <input name="date" type="text" class="form-control date-picker" placeholder="Date" />
                </div>
                <div class="form-group fg-line">
                    <label>Date Period</label>
                    <div class="row">
                        <div class="col-md-6 m-b-20">
                            <input name="from_date" type="text" class="form-control date-picker" placeholder="From Date" />
                        </div>
                        <div class="col-md-6">
                            <input name="to_date" type="text" class="form-control date-picker" placeholder=" To Date" />
                        </div>
                    </div>    
                </div>
		        
                <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
		    </div>
		 </div>
	 </form>
</div>
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}