bharath_expo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^web/', include(('web.urls', 'web'), namespace="web")),

    url(r'^$',general_views.app,name='app'),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/android/$',general_views.download_app,name='download_app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/shop/create/$',general_views.create_shop,name='create_shop'),
    url(r'^app/shop/switch/$', general_views.switch_shop, name='switch_shop'),
    url(r'^app/theme/switch/$', general_views.switch_theme, name='switch_theme'),
    url(r'^app/shop/delete/(?P<pk>.*)/$', general_views.delete_shop, name='delete_shop'),
    url(r'^app/report/$',general_views.reports,name='report'),

    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'),

    url(r'^app/customers/', include(('customers.urls','customers'), namespace="customers")),
    url(r'^app/products/', include(('products.urls','products'), namespace="products")),
    url(r'^app/sales/', include(('sales.urls','sales'), namespace="sales")),
    url(r'^app/staffs/', include(('staffs.urls','staffs'), namespace='staffs')),
    url(r'^app/vendors/', include(('vendors.urls','vendors'), namespace='vendors')),
    url(r'^app/purchases/', include(('purchases.urls', 'purchases'), namespace='purchases')),
    url(r'^app/finance/', include(('finance.urls', 'finance'), namespace="finance")),
    url(r'^app/tasks/', include(('tasks.urls','tasks'), namespace="tasks")),
    url(r'^app/distributors/', include(('distributors.urls', 'distributors'), namespace="distributors")),

    url(r'^app/users/', include(('users.urls','users'), namespace="users")),

    url(r'^app/reports/', include(('reports.urls','reports'), namespace="reports")),

    url(r'^app/barcode/create/(?P<code>.*)/$', general_views.create_barcode, name='create_barcode'),

    url(r'^create-shop-request/$', general_views.create_shop_request, name="create_shop_request"),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

staffs/urls.py
from django.conf.urls import url
from . import views
from staffs.views import DesignationAutocomplete,StaffAutocomplete

urlpatterns = [
    url(r'^designation-autocomplete/$',DesignationAutocomplete.as_view(create_field='name'),name='designation_autocomplete'),
	url(r'^staff-autocomplete/$',StaffAutocomplete.as_view(),name='staffs_autocomplete'),

    url(r'^designation/create/$', views.create_designation, name='create_designation'),
    url(r'^designations/$', views.designations, name='designations'),
    url(r'^designation/edit/(?P<pk>.*)/$', views.edit_designation, name='edit_designation'),
    url(r'^designation/(?P<pk>.*)/$', views.designation, name='designation'),
    url(r'^delete-designation/(?P<pk>.*)/$', views.delete_designation, name='delete_designation'),
    url(r'^designation/delete-selected/$', views.delete_selected_designations, name='delete_selected_designations'),

    url(r'^staff/create/$', views.create_staff, name='create_staff'),
    url(r'^staffs/$', views.staffs, name='staffs'),
    url(r'^staff/edit/(?P<pk>.*)/$', views.edit_staff, name='edit_staff'),
    url(r'^staff/(?P<pk>.*)/$', views.staff, name='staff'),
    url(r'^staff-delete/(?P<pk>.*)/$', views.delete_staff, name='delete_staff'),
    url(r'^staff/delete-selected/$', views.delete_selected_staffs, name='delete_selected_staffs'),

    url(r'^staff-salary/create/$',views.create_staff_salary,name='create_staff_salary'),
    url(r'^staff-salaries/view/$',views.staff_salaries,name='staff_salaries'),
    url(r'^staff-salary/view/(?P<pk>.*)/$',views.staff_salary,name='staff_salary'),
    url(r'^staff-salary/edit/(?P<pk>.*)/$',views.edit_staff_salary,name='edit_staff_salary'),
    url(r'^staff-salary/delete/(?P<pk>.*)/$',views.delete_staff_salary,name='delete_staff_salary'),
    url(r'^delete-selected-staff-salaries/$', views.delete_selected_staff_salaries, name='delete_selected_staff_salaries'),

    url(r'^get-salary/$',views.get_salary,name='get_salary'),

]

users/urls.py
from django.conf.urls import url,include
from . import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^view/(?P<pk>.*)/$', views.view, name='view'),
    
    url(r'^check-notification/$', views.check_notification, name='check_notification'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notification/delete/(?P<pk>.*)/$', views.delete_notification, name='delete_notification'),
    url(r'^delete-selected-notifications/$', views.delete_selected_notifications, name='delete_selected_notifications'),
    url(r'^notification/read/(?P<pk>.*)/$', views.read_notification, name='read_notification'),
    url(r'^read-selected-notifications/$', views.read_selected_notifications, name='read_selected_notifications'),
    
    url(r'^set-user-timezone/$', views.set_user_timezone, name='set_user_timezone'),
    url(r'^settings/$', views.settings, name='settings'), 
    url(r'^settings/update-shop/$', views.update_shop, name='update_shop'),

    url(r'^user/create/(?P<pk>.*)/$', views.create_user, name='create_user'),
    url(r'^user/view/(?P<pk>.*)/$', views.view_user, name='view_user'),
    url(r'^users/$', views.users, name='users'), 
    url(r'^user/delete/(?P<pk>.*)/$', views.delete_user, name='delete_user'),
    url(r'^user/delete-selected/$', views.delete_selected_users, name='delete_selected_users'),
    url(r'^change-permissions/(?P<pk>.*)/$', views.change_permissions, name='change_permissions'),
    url(r'^change-password/(?P<pk>.*)/$', views.change_password, name='change_password'),

    url(r'^revoke-access/(?P<pk>.*)/$', views.revoke_access, name='revoke_access'), 

    url(r'^activities/$', views.user_activities, name='user_activities'),
    url(r'^activity/(?P<pk>.*)/$', views.user_activity, name='user_activity'),
    
    
]

web/urls.py
from django.conf.urls import url,include
from . import views
from web.views import ProductCategoryAutocomplete,WebProductAutocomplete


urlpatterns = [
    url(r'^$', views.index,name='index'), 
    url(r'^product-category-autocomplete/$',ProductCategoryAutocomplete.as_view(),name='product_category_autocomplete'),
    url(r'^web-product-autocomplete/$',WebProductAutocomplete.as_view(),name='web_product_autocomplete'),

    url(r'^create-about/$',views.create_about,name='create_about'),
    url(r'^edit-about/(?P<pk>.*)/$',views.edit_about,name='edit_about'),
    url(r'^view-abouts/$',views.abouts,name='abouts'),
    url(r'^view-about/(?P<pk>.*)/$',views.about,name='about'),
    url(r'^delete-about/(?P<pk>.*)/$',views.delete_about,name='delete_about'),
    url(r'^delete-selected-abouts/$', views.delete_selected_abouts, name='delete_selected_abouts'),

    url(r'^category/create/$',views.create_category,name='create_category'),
    url(r'^categories/$',views.categories,name='categories'),
    url(r'^category/edit/(?P<pk>.*)/$',views.edit_category,name='edit_category'),
    url(r'^category/view/(?P<pk>.*)/$',views.category,name='category'),
    url(r'^category/delete/(?P<pk>.*)/$',views.delete_category,name='delete_category'),
    url(r'^category/delete-selected/$', views.delete_selected_categories, name='delete_selected_categories'),

    url(r'^offer/create/$',views.create_offer,name='create_offer'),
    url(r'^offer/view/$',views.offers,name='offers'),
    url(r'^offer/edit/(?P<pk>.*)/$',views.edit_offer,name='edit_offer'),
    url(r'^offer/view/(?P<pk>.*)/$',views.offer,name='offer'),
    url(r'^offer/delete/(?P<pk>.*)/$',views.delete_offer,name='delete_offer'),
    url(r'^offer/delete-selected-offers/$', views.delete_selected_offers, name='delete_selected_offers'), 

    url(r'^product/create/$',views.create_product,name='create_product'),
    url(r'^product/views/$',views.products,name='products'),
    url(r'^product/edit/(?P<pk>.*)/$',views.edit_product,name='edit_product'),
    url(r'^product/view/(?P<pk>.*)/$',views.product,name='product'),
    url(r'^product/delete/(?P<pk>.*)/$',views.delete_product,name='delete_product'),
    url(r'^product/delete-selected/$', views.delete_selected_products, name='delete_selected_products'),

    url(r'^get-products/$',views.get_products,name='get_products'),

]

staffs/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _
from main.models import BaseModel, Shop
from decimal import Decimal


GENDER_CHOICES = (
	('M','Male'),
	('F','Female'),
	('O','Other')
)

SALARY_TYPE = (
	('daily','Daily'),
	('monthly','Monthly')
)

MONTH = (
	('1','January'),
	('2','February'),
	('3','March'),
	('4','April'),
	('5','May'),
	('6','June'),
	('7','July'),
	('8','August'),
	('9','September'),
	('10','October'),
	('11','November'),
	('12','December'),
)


class Designation(BaseModel):
	shop = models.ForeignKey("main.Shop",on_delete=models.CASCADE)
	name = models.CharField(max_length=128)

	is_deleted = models.BooleanField(default=False)

	class Meta:
		db_table = 'staffs_designation'
		verbose_name = _('designation')
		verbose_name_plural = _('designations')

	def __unicode__(self):
		return self.name


class Staff(BaseModel):
	distributor = models.ForeignKey("distributors.Distributor",blank=True,null=True,on_delete=models.CASCADE)
	shop = models.ForeignKey("main.Shop",on_delete=models.CASCADE)
	user = models.OneToOneField("auth.user",blank=True,null=True,on_delete=models.CASCADE)
	first_name = models.CharField(max_length=128)
	last_name = models.CharField(max_length=128,blank=True,null=True)
	phone = models.CharField(max_length=15,null=True)
	gender = models.CharField(max_length=5,choices=GENDER_CHOICES)
	dob = models.DateField(blank=True,null=True)
	joined_date = models.DateField()
	salary_type = models.CharField(max_length=30,choices=SALARY_TYPE)
	designation = models.ForeignKey("staffs.Designation",blank=True,null=True,on_delete=models.CASCADE)
	salary = models.DecimalField(default=0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
	photo = models.ImageField(upload_to="uploads/staffs/",blank=True,null=True)
	permissions = models.ManyToManyField("users.Permission")
	
	credit = models.DecimalField(default=0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
	debit = models.DecimalField(default=0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])

	is_deleted = models.BooleanField(default=False)

	def permissionlist(self):
		permlist = list(set([x.code for x in self.permissions.all()]))
		
		return permlist
		
	class Meta:
		db_table = 'staffs_staff'
		verbose_name = _('staff')
		verbose_name_plural = _('staffs')

	def __unicode__(self):
		return self.first_name +" " + self.last_name


class StaffSalary(BaseModel):
	shop = models.ForeignKey("main.Shop",on_delete=models.CASCADE)
	staff = models.ForeignKey("staffs.Staff",on_delete=models.CASCADE)
	from_date = models.DateField()
	to_date = models.DateField()
	days = models.PositiveIntegerField()
	time = models.DateTimeField()
	basic_salary = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
	allowance = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))]) 
	deduction = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])    
	total_amount = models.DecimalField(default=0.0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])
	is_deleted = models.BooleanField(default=False)
	commission_amount = models.DecimalField(default=0,decimal_places=2, max_digits=15,validators=[MinValueValidator(Decimal('0.00'))])

	class Meta:
		db_table = 'staffs_staffsalary'
		verbose_name = _('staffsalary')
		verbose_name_plural = _('staffsalaries')
		ordering = ('-a_id',)
		
	def __unicode__(self):
		return self.staff

staffs/forms.py
from django import forms
from django.forms.widgets import TextInput, Textarea, HiddenInput, Select
from staffs.models import Staff, Designation, StaffSalary
from django.utils.translation import ugettext_lazy as _
from dal import autocomplete


class DesignationForm(forms.ModelForm):

    class Meta:
        model = Designation
        exclude = ['creator', 'updator', 'auto_id', 'is_deleted', 'a_id','shop']
        widgets = {
            'name': TextInput(attrs={'class': 'required form-control', 'placeholder': 'Name'})
        }
        error_messages = {
            'name': {
                'required': _("Name field is required."),
            }
        }


class StaffForm(forms.ModelForm):

    class Meta:
        model = Staff
        exclude = ['creator', 'updator', 'auto_id', 'is_deleted', 'a_id','user','shop','permissions','credit','debit']
        widgets = {
            'distributor': autocomplete.ModelSelect2(url='distributors:distributor_autocomplete', attrs={'data-placeholder': 'Distributor', 'data-minimum-input-length': 1},),
            'first_name': TextInput(attrs={'class': 'required form-control', 'placeholder': 'First Name'}),
            'last_name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            'designation': autocomplete.ModelSelect2(url='staffs:designation_autocomplete', attrs={'data-placeholder': 'Designation', 'data-minimum-input-length': 1},),
            'salary': TextInput(attrs={'class': 'required form-control', 'placeholder': 'Salary'}),
            'phone': TextInput(attrs={'class': 'required form-control', 'placeholder': 'Phone'}),
            'gender': Select(attrs={'class': 'required form-control selectpicker', 'placeholder': 'Gender'}),
            'salary_type': Select(attrs={'class': 'required form-control selectpicker'}),
            'dob': TextInput(attrs={'class': 'required form-control date-picker', 'placeholder': 'Date Of Birth'}),
            'joined_date': TextInput(attrs={'class': 'required form-control date-picker', 'placeholder': 'Joined DAte'}),
        }
        error_messages = {
            'first_name': {
                'required': _("First Name field is required."),
            },
            'designation': {
                'required': _("Designation field is required."),
            },
            'salary': {
                'required': _("Salary field is required."),
            },
            'phone': {
                'required': _("phone field is required."),
            },
            'gender': {
                'required': _("Sex field is required."),
            },
            'salary_type': {
                'required': _("Salary Type field is required."),
            },
            'joined_date': {
                'required': _("Joined Date field is required."),
            },
            'dob': {
                'required': _("DOB field is required."),
            },
            'photo' : {
            'required' : _("Photo field is required."),
            },
            'image' : {
            'required' : _("Image field is required."),
            }
        }
        labels = {
            'dob' : 'Date of birth'
        }



class StaffSalaryForm(forms.ModelForm):
    
    class Meta:
        model=StaffSalary
        exclude = ['creator','updator','auto_id','is_deleted','a_id','shop','total_amount']            
        widgets = {
            'staff': autocomplete.ModelSelect2(url='staffs:staffs_autocomplete', attrs={'data-placeholder': 'Staff', 'data-minimum-input-length': 1},),
            'from_date': TextInput(attrs={'class': 'date-picker form-control','placeholder' : 'From date'}),
            'to_date': TextInput(attrs={'class': 'form-control date-picker','placeholder' : 'To Date'}),
            'days': TextInput(attrs={'class': 'form-control','placeholder' : 'No. days'}),
            'basic_salary': TextInput(attrs={'class': 'form-control','placeholder' : 'Basic Salary'}),
            'allowance': TextInput(attrs={'class': 'form-control','placeholder' : 'Allowance'}),
            'deduction': TextInput(attrs={'class': 'form-control','placeholder' : 'Deduction'}),
            'commission_amount': TextInput(attrs={'class': 'form-control','placeholder' : 'Commission Amount'}),
        }
        error_messages = {
            'staff' : {
                'required' : _("Staff field is required."),
            },
            'date' : {
                'required' : _("Date field is required."),
            },
            'amount' : {
                'required' : _("Amount field is required."),
            },
            'commission_amount' : {
                'required' : _("Commission Amount field is required."),
            }
        }
    def clean(self):
        cleaned_data=super(StaffSalaryForm, self).clean()
        staff = self.cleaned_data.get('staff')
        from_date = self.cleaned_data.get('from_date')
        if StaffSalary.objects.filter(staff__pk=staff.pk,is_deleted=False).exists():
            staff_salaries = StaffSalary.objects.filter(staff__pk=staff.pk,is_deleted=False).exclude(pk=self.instance.pk)
            for staff_salary in staff_salaries:
                if staff_salary.to_date > from_date or staff_salary.to_date == from_date:
                    raise forms.ValidationError(
                        "Salary already paid"
                    )
        return cleaned_data

templates/staffs/designations/designation.html
{% extends "base.html" %}
{% load i18n %}

{% load users_template_tags %}
{% block content %}
	<section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{title}}</h2>
            </div>
            
            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{instance.name}}</div>

                <ul class="ah-actions actions a-alt">
                    {% if is_superuser or 'can_create_designation' in user_instance.permissionlist %}
                    <li>
                        <a title="Add Designation" href="{% url 'staffs:create_designation' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
                    {% endif %}
                    {% if is_superuser or 'can_modify_designation' in user_instance.permissionlist %}
                    <li>
                        <a title="Edit Designation" href="{% url 'staffs:edit_designation' pk=instance.pk %}">
                            <i class="zmdi zmdi-edit"></i>
                        </a>
                    </li>
                    {% endif %}
                    {% if is_superuser or 'can_delete_designation' in user_instance.permissionlist %}
                    <li>
                        <a title="Delete Designation" data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'staffs:delete_designation' pk=instance.pk %}" class="action-button redirect">
                            <i class="zmdi zmdi-delete"></i>
                        </a>
                    </li> 
                    {% endif %}                               
                </ul>
            </div>

            <div id="c-grid" class="clearfix" data-columns="2">
                <div class="card">
                    <div class="card-header">
                        <h2>Basic Info <small></small></h2>
                    </div>

                    <div class="card-body">
                        <div class="list-group lg-alt c-overflow">
                            <div class="list-group-item media">

                                <div class="media-body">
                                    <div class="lgi-heading">Name</div>
                                    <small class="lgi-text">{{instance.name}}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="card">
                    <div class="card-header">
                        <h2>Created &amp; Updated <small></small></h2>
                    </div>

                    <div class="card-body">
                        <div class="list-group lg-alt c-overflow">
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Date Added</div>
                                    <small class="lgi-text">{{instance.date_added}}</small>
                                </div>
                            </div>
                            
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Date Updated</div>
                                    <small class="lgi-text">{{instance.date_updated}}</small>
                                </div>
                            </div>
                            
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Created User</div>
                                    <small class="lgi-text"><a href="{% url 'users:view' pk=instance.creator.username %}">{{instance.creator.username|get_user_name}}</a></small>
                                </div>
                            </div>
                            
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Last Updated User</div>
                                    <small class="lgi-text"><a href="{% url 'users:view' pk=instance.updator.username %}">{{instance.updator.username|get_user_name}}</a></small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
             </div>                    
        </div>
    </section>
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}

templates/staffs/designations/designations.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <section id="content">
        <div class="container">
             <div class="c-header">
                <h2>{{title}}</h2>
            </div>
            
            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{title}}</div>
    
                <div class="ah-search">
                    <form method="get" action="{% url 'staffs:designations' %}">
                        <input name="q" type="text" placeholder="Start typing..." class="ahs-input">
    
                        <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                        <input type="submit" class="hidden" />
                    </form>
                </div>
    
                <ul class="ah-actions actions a-alt">
                    <li>
                        <a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
                            <i class="zmdi zmdi-search"></i>
                        </a>
                    </li>
                    
                    <li>
                        <a title="Filter" class="filter_button" href="">
                            <i class="zmdi zmdi-filter-list"></i>
                        </a>
                    </li>
                    {% if "is_superuser" or 'can_create_designation' in user_instance.permissionlist %}
                    <li>
                        <a title="Create Designation" href="{% url 'staffs:create_designation' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
                    {% endif %}
                    {% if instances %}
    
                    <li>
                        <a title="Select All" class="check_all" href="">
                            <i class="zmdi zmdi-select-all"></i>
                        </a>
                    </li>
                    {% if "is_superuser" or 'can_delete_designation' in user_instance.permissionlist %}
                    <li>
                        <a title="Delete selected Designations" data-id="" href="{% url 'staffs:delete_selected_designations' %}" data-text="{{confirm_delete_selected_message}}" data-title="Are you sure?" class="action-button reload selected-items-button">
                            <i class="zmdi zmdi-delete"></i>
                        </a>
                    </li>
                    {% endif %}
                    {% endif %}
                </ul>
                
            </div>

            <div class="card">
                
                {% if instances %}
                
                <div class="table-responsive">
                    <table id="data-table-basic" class="table table-striped table-vmiddle">
                        <thead>
                            <tr>
                                <th style="width:20px;"></th>
                                <th>Id</th>
                                <th>Name</th>
                                <th data-column-id="action">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% load el_pagination_tags %}
                            {% paginate 21 instances %}
                            {% for instance in instances %}
                            <tr class="check_items_row">
                                <td style="width:20px;">
                                    <div class="checkbox lgi-checkbox m-t-5">
                                        <label>
                                            <input class="check check_item" type="checkbox" value="{{instance.pk}}" name="delete_item">
                                            <i class="input-helper"></i>
                                        </label>
                                    </div>
                                </td>
                                <td>{{instance.auto_id}}</td>
                                <td>{{instance.name}}</td>
                                <td>
                                    {% if is_superuser or 'can_view_designation' in user_instance.permissionlist %}
                                    <a href="{% url 'staffs:designation' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                                    {% endif %}
                                    {% if "is_superuser" or 'can_modify_designation' in user_instance.permissionlist %}
                                    <a href="{% url 'staffs:edit_designation' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i title="Edit designation" class="zmdi zmdi-edit"></i></a>
                                    {% endif %}
                                    {% if is_superuser or 'can_delete_designation' in user_instance.permissionlist %}
                                    <a data-id="{{instance.pk}}" href="{% url 'staffs:delete_designation' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                                    {% endif %}
                                    
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                
                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                    {% get_pages %}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="pagination">
                                {% show_pages %}
                            </div>
                        </div>
                        <div class="col-sm-6 infoBar">
                            <div class="infos">
                                Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                            </div>
                        </div>
                    </div>
                </div>   
                <!--pagination-->
                {% else %}
                    {% include 'includes/not_found.html' %}
                {% endif %}            
            </div>
            
        </div>
    </section>
{% endblock %}

{% block filter_box %}
<div class="filter-box">
     <form method="get" action="">
        <div class="card">
            <div class="card-header">
                <h2>Filter <small></small></h2>
                <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i> Back</span>
            </div>
            
            <div class="card-body card-padding">
                <div class="form-group fg-line">
                    <label>Query</label>
                    <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
                </div>
                
                 <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
            </div>
         </div>
     </form>
</div>
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}