bharath_expo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^web/', include(('web.urls', 'web'), namespace="web")),

    url(r'^$',general_views.app,name='app'),
    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/android/$',general_views.download_app,name='download_app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/shop/create/$',general_views.create_shop,name='create_shop'),
    url(r'^app/shop/switch/$', general_views.switch_shop, name='switch_shop'),
    url(r'^app/theme/switch/$', general_views.switch_theme, name='switch_theme'),
    url(r'^app/shop/delete/(?P<pk>.*)/$', general_views.delete_shop, name='delete_shop'),
    url(r'^app/report/$',general_views.reports,name='report'),

    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'),

    url(r'^app/customers/', include(('customers.urls','customers'), namespace="customers")),
    url(r'^app/products/', include(('products.urls','products'), namespace="products")),
    url(r'^app/sales/', include(('sales.urls','sales'), namespace="sales")),
    url(r'^app/staffs/', include(('staffs.urls','staffs'), namespace='staffs')),
    url(r'^app/vendors/', include(('vendors.urls','vendors'), namespace='vendors')),
    url(r'^app/purchases/', include(('purchases.urls', 'purchases'), namespace='purchases')),
    url(r'^app/finance/', include(('finance.urls', 'finance'), namespace="finance")),
    url(r'^app/tasks/', include(('tasks.urls','tasks'), namespace="tasks")),
    url(r'^app/distributors/', include(('distributors.urls', 'distributors'), namespace="distributors")),

    url(r'^app/users/', include(('users.urls','users'), namespace="users")),

    url(r'^app/reports/', include(('reports.urls','reports'), namespace="reports")),

    url(r'^app/barcode/create/(?P<code>.*)/$', general_views.create_barcode, name='create_barcode'),

    url(r'^create-shop-request/$', general_views.create_shop_request, name="create_shop_request"),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

customers/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from customers.views import CustomerAutocomplete


urlpatterns = [
    url(r'^customer-autocomplete/$',CustomerAutocomplete.as_view(),name='customer_autocomplete'),

    url(r'^$', views.dashboard,name='dashboard'),

    url(r'^customer/create/$',views.create,name='create'),
    url(r'^customer/view/$',views.customers,name='customers'),
    url(r'^customer/edit/(?P<pk>.*)/$',views.edit,name='edit'),
    url(r'^customer/views/(?P<pk>.*)/$',views.customer,name='customer'),
    url(r'^customer/delete/(?P<pk>.*)/$',views.delete,name='delete'),
    url(r'^customer/delete-selected/$', views.delete_selected_customers, name='delete_selected_customers'),

    url(r'^get-debit/$', views.get_credit, name='get_credit'),
    url(r'^get-customer-discount/$', views.get_customer_discount, name='get_customer_discount'),
    url(r'^check-sale-restriction/$', views.check_sale_restriction, name='check_sale_restriction'),
]

reports/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^sale-report$', views.sale_report,name='sale_report'), 
    url(r'^print-report/$', views.print_report,name='print_report'), 
    url(r'^taxed-sale-items/$', views.taxed_sale_items,name='taxed_sale_items'),
    url(r'^export-report/$', views.export_report,name='export_report'),
    url(r'^gstr1/$', views.gstr1,name='gstr1'),
    url(r'^create-sale-report/$', views.create_sale_report,name='create_sale_report'),

    url(r'^print-daily-report/$', views.print_daily_report,name='print_daily_report'),
    url(r'^create-daily-report/$', views.create_daily_report,name='create_daily_report'),

    url(r'^print-distributor-report/$', views.print_distributor_report,name='print_distributor_report'),
    url(r'^create-distributor-report/$', views.create_distributor_report,name='create_distributor_report'),

    url(r'^print-manufacture-report/$', views.print_manufacture_report,name='print_manufacture_report'),
    url(r'^create-manufacture-report/$', views.create_manufacture_report,name='create_manufacture_report'),

    url(r'^print-monthly-report/$', views.print_monthly_report,name='print_monthly_report'),
    url(r'^create-monthly-report/$', views.create_monthly_report,name='create_monthly_report'),

    url(r'^print-collect_amount-report/$', views.print_collect_amount_report,name='print_collect_amount_report'),
    url(r'^create-collect_amount-report/$', views.create_collect_amount_report,name='create_collect_amount_report'),

    url(r'^create-performance-report/$', views.create_performance_report,name='create_performance_report'),    
    url(r'^print-performance-report/$', views.print_performance_report,name='print_performance_report'),

    url(r'^create-customer-report/$', views.create_customer_report,name='create_customer_report'),    
    url(r'^print-customer-report/$', views.print_customer_report,name='print_customer_report'),

    url(r'^create-return-report/$', views.create_return_report,name='create_return_report'),    
    url(r'^print-return-report/$', views.print_return_report,name='print_return_report'),
]

sales/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from sales.views import SaleAutocomplete,ReturnableProductAutocomplete


urlpatterns = [               
    url(r'^sale-autocomplete/$',SaleAutocomplete.as_view(),name='sale_autocomplete'),
    url(r'^returnable_products-autocomplete/$',ReturnableProductAutocomplete.as_view(),name='returnable_product_autocomplete'),
    
    url(r'^$', views.dashboard,name='dashboard'), 
    url(r'^print-report/$', views.print_report,name='print_report'), 
    url(r'^taxed-sale-items/$', views.taxed_sale_items,name='taxed_sale_items'),
    url(r'^export-report/$', views.export_report,name='export_report'),
    
    url(r'^sale/create/$',views.create,name='create'),
    url(r'^sale/views/$',views.sales,name='sales'),
    url(r'^sale/edit/(?P<pk>.*)/$',views.edit,name='edit'),
    url(r'^sale/view/(?P<pk>.*)/$',views.sale,name='sale'),
    url(r'^sale/delete/(?P<pk>.*)/$',views.delete,name='delete'),
    url(r'^sale/delete-selected/$', views.delete_selected_sales, name='delete_selected_sales'),
    url(r'^invoice/(?P<pk>.*)/$',views.print_sale,name='print'),
    url(r'^email/(?P<pk>.*)/$',views.email_sale,name='email_sale'),
    url(r'^return-sale/views/$',views.return_sales,name='return_sales'),

    url(r'^collect-amount/create/$', views.create_collect_amount, name='create_collect_amount'),
    url(r'^collect-amount/view/(?P<pk>.*)/$', views.collect_amount, name='collect_amount'),
    url(r'^collect-amount/edit/(?P<pk>.*)/$', views.edit_collect_amount, name='edit_collect_amount'),
    url(r'^collect-amounts/$', views.collect_amounts, name='collect_amounts'),
    url(r'^collect-amount/delete/(?P<pk>.*)/$', views.delete_collect_amount, name='delete_collect_amount'),
    url(r'^collect-amount/delete-selected/$', views.delete_selected_collect_amounts, name='delete_selected_collect_amounts'),
    url(r'^collected-amount/print/(?P<pk>.*)/$',views.print_collected_amount,name='print_collected_amount'),
    url(r'^collected-amounts/print/$',views.print_collected_amounts,name='print_collected_amounts'),

    url(r'^customer-payment/create/$', views.create_customer_payment, name='create_customer_payment'),
    url(r'^customer-payment/view/(?P<pk>.*)/$', views.customer_payment, name='customer_payment'),
    url(r'^customer-payment/edit/(?P<pk>.*)/$', views.edit_customer_payment, name='edit_customer_payment'),
    url(r'^customer-payments/$', views.customer_payments, name='customer_payments'),
    url(r'^customer-payment/delete/(?P<pk>.*)/$', views.delete_customer_payment, name='delete_customer_payment'),
    url(r'^customer-payment/delete-selected/$', views.delete_selected_customer_payments, name='delete_selected_customer_payments'),
    url(r'^customer-payment/print/(?P<pk>.*)/$',views.print_customer_payment,name='print_customer_payment'),
    url(r'^customer-payments/print/$',views.print_customer_payments,name='print_customer_payments'),

    url(r'^create-sale-return/$',views.create_sale_return,name='create_sale_return'),
    url(r'^sale-returns/$',views.sale_returns,name='sale_returns'), 
    url(r'^sale-return/(?P<pk>.*)/$', views.sale_return, name='sale_return'),

    url(r'^print-sale-return/(?P<pk>.*)/$', views.print_sale_return, name='print_sale_return'),
    url(r'^delete-sale-return/(?P<pk>.*)/$', views.delete_sale_return, name='delete_sale_return'),

    url(r'^damaged-products/$',views.damaged_products,name='damaged_products'),
    url(r'^create-damaged-product/$',views.create_damaged_product,name='create_damaged_product'),
    
    url(r'^create-product-return/$',views.create_product_return,name='create_product_return'),
    url(r'^product-return/(?P<pk>.*)/$', views.product_return, name='product_return'),
    url(r'^product-returns/$',views.product_returns,name='product_returns'),
    url(r'^delete-product-return/(?P<pk>.*)/$', views.delete_product_return, name='delete_product_return'),
    url(r'^get-sale-items/$', views.get_sale_items,name='get_sale_items'),
    url(r'^get-return-items/$', views.get_return_items,name='get_return_items'),
    url(r'^get-vendor-return-items/$', views.get_vendor_return_items,name='get_vendor_return_items'),
    url(r'^get-customer/$', views.get_customer,name='get_customer'),

    url(r'^estimate/create/$',views.create_estimate,name='create_estimate'),
    url(r'^estimate/views/$',views.estimates,name='estimates'),
    url(r'^estimate/edit/(?P<pk>.*)/$',views.edit_estimate,name='edit_estimate'),
    url(r'^estimate/view/(?P<pk>.*)/$',views.estimate,name='estimate'),
    url(r'^estimate/delete/(?P<pk>.*)/$',views.delete_estimate,name='delete_estimate'),
    url(r'^estimate/delete-selected/$', views.delete_selected_estimates, name='delete_selected_estimates'),
    url(r'^print-estimate/(?P<pk>.*)/$',views.print_estimate,name='print_estimate'),
    url(r'^email-estimate/(?P<pk>.*)/$',views.email_estimate,name='email_estimate'),

    url(r'^stock/report/$',views.stock_report, name='stock_report'),

    url(r'^create-vendor-return/$',views.create_vendor_return,name='create_vendor_return'),
    url(r'^vendor-return/(?P<pk>.*)/$', views.vendor_return, name='vendor_return'),
    url(r'^vendor-returns/$',views.vendor_returns,name='vendor_returns'),
    url(r'^delete-vendor-return/(?P<pk>.*)/$', views.delete_vendor_return, name='delete_vendor_return'), 

    url(r'^purchase-request/create/$',views.create_purchase_request,name='create_purchase_request'),
    url(r'^purchase-request/views/$',views.purchase_requests,name='purchase_requests'),
    url(r'^purchase-request/edit/(?P<pk>.*)/$',views.edit_purchase_request,name='edit_purchase_request'),
    url(r'^purchase-request/view/(?P<pk>.*)/$',views.purchase_request,name='purchase_request'),
    url(r'^purchase-request/delete/(?P<pk>.*)/$',views.delete_purchase_request,name='delete_purchase_request'),
    url(r'^purchase-request/delete-selected/$', views.delete_selected_purchase_requests, name='delete_selected_purchase_requests'),
    url(r'^print-purchase-request/(?P<pk>.*)/$',views.print_purchase_request,name='print_purchase_request'),

    url(r'^purchase-request/returns/$',views.purchase_request_returns,name='purchase_request_returns'),

    url(r'^purchase-request-sale/create/(?P<pk>.*)/$',views.purchase_request_sale_create,name='purchase_request_sale_create'),
    url(r'^cheque-list/views/$',views.cheque_lists,name='cheque_lists'),
    url(r'^cheque_withdraw/(?P<pk>.*)/$',views.cheque_withdraw,name='cheque_withdraw'),
    url(r'^cheque_return/(?P<pk>.*)/$',views.cheque_return,name='cheque_return'),

]

vendors/urls.py
from django.conf.urls import url
from vendors.views import VendorAutocomplete
from . import views


urlpatterns = [

    url(r'^vendor-autocomplete/$',VendorAutocomplete.as_view(),name='vendor_autocomplete'),


    url(r'^vendor/create/$', views.create_vendor, name='create_vendor'),
    url(r'^vendors/$', views.vendors, name='vendors'),
    url(r'^vendor/edit/(?P<pk>.*)/$', views.edit_vendor, name='edit_vendor'),
    url(r'^vendor/view/(?P<pk>.*)/$', views.vendor, name='vendor'),
    url(r'^vendor/delete/(?P<pk>.*)/$', views.delete_vendor, name='delete_vendor'),
    url(r'^vendor/delete-selected/$', views.delete_selected_vendors, name='delete_selected_vendors'),

    url(r'^get-debit/$', views.get_debit, name='get_debit'),
]

web/urls.py
from django.conf.urls import url,include
from . import views
from web.views import ProductCategoryAutocomplete,WebProductAutocomplete


urlpatterns = [
    url(r'^$', views.index,name='index'), 
    url(r'^product-category-autocomplete/$',ProductCategoryAutocomplete.as_view(),name='product_category_autocomplete'),
    url(r'^web-product-autocomplete/$',WebProductAutocomplete.as_view(),name='web_product_autocomplete'),

    url(r'^create-about/$',views.create_about,name='create_about'),
    url(r'^edit-about/(?P<pk>.*)/$',views.edit_about,name='edit_about'),
    url(r'^view-abouts/$',views.abouts,name='abouts'),
    url(r'^view-about/(?P<pk>.*)/$',views.about,name='about'),
    url(r'^delete-about/(?P<pk>.*)/$',views.delete_about,name='delete_about'),
    url(r'^delete-selected-abouts/$', views.delete_selected_abouts, name='delete_selected_abouts'),

    url(r'^category/create/$',views.create_category,name='create_category'),
    url(r'^categories/$',views.categories,name='categories'),
    url(r'^category/edit/(?P<pk>.*)/$',views.edit_category,name='edit_category'),
    url(r'^category/view/(?P<pk>.*)/$',views.category,name='category'),
    url(r'^category/delete/(?P<pk>.*)/$',views.delete_category,name='delete_category'),
    url(r'^category/delete-selected/$', views.delete_selected_categories, name='delete_selected_categories'),

    url(r'^offer/create/$',views.create_offer,name='create_offer'),
    url(r'^offer/view/$',views.offers,name='offers'),
    url(r'^offer/edit/(?P<pk>.*)/$',views.edit_offer,name='edit_offer'),
    url(r'^offer/view/(?P<pk>.*)/$',views.offer,name='offer'),
    url(r'^offer/delete/(?P<pk>.*)/$',views.delete_offer,name='delete_offer'),
    url(r'^offer/delete-selected-offers/$', views.delete_selected_offers, name='delete_selected_offers'), 

    url(r'^product/create/$',views.create_product,name='create_product'),
    url(r'^product/views/$',views.products,name='products'),
    url(r'^product/edit/(?P<pk>.*)/$',views.edit_product,name='edit_product'),
    url(r'^product/view/(?P<pk>.*)/$',views.product,name='product'),
    url(r'^product/delete/(?P<pk>.*)/$',views.delete_product,name='delete_product'),
    url(r'^product/delete-selected/$', views.delete_selected_products, name='delete_selected_products'),

    url(r'^get-products/$',views.get_products,name='get_products'),

]

reports/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

templates/includes/dashboard/distributor_dashboard.html
<div class="card card-padding">
    <div class="card-body card-padding">
        <div class="row m-b-10">

            <div class="col-sm-3">
                <h1 id="id_total_sales_amount_top" class="m-b-xs c-bluegray">0.00</h1>
                <h4 class='c-bluegray'>Total Sales</h4>
                <div id="sparkline1" class="m-b-sm"></div>
                <div class="row">
                    <div class="col-xs-4 p-l-10 p-r-10">
                        <small class="stats-label c-brown">Sale Count</small>
                        <h4 id="id_total_sales_created" class ='c-brown'>0.00</h4>
                    </div>

                    <div class="col-xs-4 p-l-10 p-r-10">
                        <small class="stats-label c-brown">Sale Amount</small>
                        <h4 id="id_total_sales_amount" class ='c-brown'>0.00</h4>
                    </div>
                    <div class="col-xs-4 p-l-10 p-r-10">
                        <small class="stats-label c-brown">Collected Amount</small>
                        <h4 id="id_total_other_income" class ='c-brown'>0.00</h4>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <h1 id="id_total_sale_return_amount" class="m-b-xs c-bluegray">0.00</h1>
                <h4 class='c-bluegray'>Sale Return</h4>
                <div id="sparkline2" class="m-b-sm"></div>
                <div class="row">
                    <div class="col-xs-4 p-l-10 p-r-10">
                        <small class="stats-label c-brown">Return Count</small>
                        <h4 id="id_return_count" class ='c-brown'>0.00</h4>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <h1 id="id_this_period_total_expense_amount_total" class="m-b-xs c-bluegray">0.00</h1>
                <h4 class='c-bluegray'>Other Expense</h4>
                <div id="sparkline2" class="m-b-sm"></div>
                <div class="row">
                    <div class="col-xs-4 p-l-10 p-r-10">
                        <small class="stats-label c-brown">Other Expense</small>
                        <h4 id="id_this_period_total_expense_amount" class ='c-brown'>0.00</h4>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">

                <div class="row m-t-xs">
                    <div class="col-xs-6">
                        <h1 id="id_current_balance" class="no-margins c-bluegray f-19">0.00</h1>
                         <h4 class="m-b-xs c-bluegray f-12">Current Balance</h4>
                    </div>
                    <div class="col-xs-6">
                        <h1 class="no-margins c-bluegray f-19">{{total_commission_amount|default:"0.00"}}</h1>
                        <h4 class="m-b-xs c-bluegray f-12">Commission</h4>
                    </div>
                    <div class="col-xs-6">
                        <h1 id="id_this_period_total_transfer_amount" class="no-margins c-bluegray f-19">0.00</h1>
                        <h4 class="m-b-xs c-bluegray f-12">Cash Transfer</h4>
                    </div>
                    <div class="col-xs-6">
                        <h1 id="id_sale_total_balance" class="no-margins c-bluegray f-19">0.00</h1>
                        <h4 class="m-b-xs c-bluegray f-12">Credit</h4>
                    </div>
                </div>
            </div>
        </div>
       <!--  <div class="row">
            <div class="col-md-8">
                <div>
                    <canvas id="lineChart" height="114"></canvas>
                </div>
            </div>
            <div class="col-md-4">
                <ul class="stat-list m-t-lg list-unstyled">
                    <li>
                        <h2 id="id_total_income" class="no-margins">0.00</h2>
                        <small>Total Income in period</small>
                        <div class="progress progress-mini">
                            <div class="progress-bar" id="id_income_progress_bar"></div>
                        </div>
                    </li>
                    <li>
                        <h2 id="id_total_expense" class="no-margins ">0.00</h2>
                        <small>Total Expense in period</small>
                        <div class="progress progress-mini">
                            <div class="progress-bar" id="id_expense_progress_bar"></div>
                        </div>
                    </li>
                </ul>
            </div>
        </div> -->
    </div>
</div>

templates/includes/dashboard/distributor_stocks.html
{% load static %}
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h2>My Stocks <small></small></h2>
        </div>

        <div class="card-body">
        	{% if product_stocks %}
            <div class="table-responsive">
                <table id="data-table-basic" class="table table-striped table-vmiddle">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Stock</th>
                        </tr>
                    </thead>
                    <tbody>
                    	{% for instance in product_stocks %}
                        <tr>
                            <td>{{instance.product.name}}</td>
                            <td>{{instance.stock}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            	<div class="card-padding card-body">
    	        	<p>No products found</p>
    	        </div>
            {% endif %}
        </div>
    </div>
</div>

templates/includes/dashboard/recent_customers.html
{% load static %}
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h2>Recent Customers <small></small></h2>
        </div>

        <div class="card-body">
            {% if recent_customers %}
            <div class="table-responsive">
                <table id="data-table-basic" class="table table-striped table-vmiddle">
                    <thead>
                        <tr>
                            <th data-column-id="id" data-type="numeric">ID</th>
                            <th>Name</th>
                            <th>Address</th>
                            <th>Phone</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for instance in recent_customers %}
                        <tr>
                            <td><a href="{% url 'customers:customer' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                            <td>{{instance.name}}</td>
                            <td>{{instance.address}}</td>
                            <td>{{instance.phone}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
                <div class="card-padding card-body">
                    <p>No customers found</p>
                </div>
            {% endif %}
        </div>
    </div>
</div>

templates/includes/dashboard/recent_products.html
{% load static %}
<div class="col-md-6">
    <div class="card">
        <div class="card-header">
            <h2>Recent Products <small></small></h2>
        </div>

        <div class="card-body">
        	{% if recent_products %}
            <div class="table-responsive">
                <table id="data-table-basic" class="table table-striped table-vmiddle">
                    <thead>
                        <tr>
                            <th data-column-id="id" data-type="numeric">ID</th>
                            <th>Name</th>
                            <th>Stock</th>
                        </tr>
                    </thead>
                    <tbody>
                    	{% for instance in recent_products %}
                        <tr>
                            <td><a href="{% url 'products:product' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                            <td>{{instance.name}}</td>
                            <td>{{instance.stock}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            	<div class="card-padding card-body">
    	        	<p>No products found</p>
    	        </div>
            {% endif %}
        </div>
    </div>
</div>

templates/includes/dashboard/recent_purchase.html
{% load static %}
<div class="card">
    <div class="card-header">
        <h2>Recent Purchase<small></small></h2>
    </div>

    <div class="card-body">
        <div class="table-responsive">
        	{% if recent_purchase %}
            <table id="data-table-basic" class="table table-striped table-vmiddle">
                <thead>
                    <tr>
                        <th data-column-id="id" data-type="numeric">ID</th>
                        <th>Time</th>
                        <th>Vendor</th>
                        <th>Sub Total</th>
                        <th>Special Discount</th>
                        <th>Total</th>
                        <th data-column-id="action" class="four">Action</th>
                    </tr>
                </thead>
                <tbody>
                	{% for instance in recent_purchase %}
                    <tr>
                        <td><a href="{% url 'purchases:purchase' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                        <td>{{instance.time}}</td>
                        <td><a href="{% url 'vendors:vendor' pk=instance.customer.pk %}">{{instance.vendor}}</a></td>
                        <td>{{instance.subtotal}}</td>
                        <td>{{instance.special_discount}}</td>
                        <td>{{instance.total}}</td>
                        <td class="four">
                        	<a href="{% url 'purchases:purchase' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                        	<a href="{% url 'purchases:edit_purchase' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                        	<a data-id="{{instance.pk}}" href="{% url 'purchases:delete_purchase' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                        	<a href="{% url 'purchases:print' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-print"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            {% else %}
            	<div class="card-body card-padding">
	            	<p>No purchases found</p>
	            </div>
            {% endif %}
        </div>
    </div>
</div>

templates/includes/dashboard/recent_sales.html
{% load static %}
<div class="card">
    <div class="card-header">
        <h2>Recent Sales <small></small></h2>
    </div>

    <div class="card-body">
        <div class="table-responsive">
        	{% if recent_sales %}
            <table id="data-table-basic" class="table table-striped table-vmiddle">
                <thead>
                    <tr>
                        <th data-column-id="id" data-type="numeric">ID</th>
                        <th>Time</th>
                        <th>Customer</th>
                        <th>Sub Total</th>
                        <th>Special Discount</th>
                        <th>Total</th>
                        <th data-column-id="action" class="four">Action</th>
                    </tr>
                </thead>
                <tbody>
                	{% for instance in recent_sales %}
                    <tr>
                        <td><a href="{% url 'sales:sale' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                        <td>{{instance.time}}</td>
                        <td><a href="{% url 'customers:customer' pk=instance.customer.pk %}">{{instance.customer}}</a></td>
                        <td>{{instance.subtotal}}</td>
                        <td>{{instance.special_discount}}</td>
                        <td>{{instance.total}}</td>
                        <td class="four">
                        	<a href="{% url 'sales:sale' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                        	<a href="{% url 'sales:edit' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                        	<a data-id="{{instance.pk}}" href="{% url 'sales:delete' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                        	<a target='_blank' href="{% url 'sales:print' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-print"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            {% else %}
            	<div class="card-body card-padding">
	            	<p>No sales found</p>
	            </div>
            {% endif %}
        </div>
    </div>
</div>